version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - dailytrends
    volumes:
      - mongodailytrends:/var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_MONGO_NAME}

networks:
  dailytrends:
    driver: bridge

volumes:
  mongodailytrends:
    driver: local