version: '3.1'

services:
  mongo:
    image: mongo:4.2-bionic
    restart: always
    ports:
      - 27017:27017
    networks:
      - dailytrends
    volumes:
      - mongodailytrends:/var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: 'dailytrends'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - dailytrends
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_MONGO_USER}:${DATABASE_MONGO_PASSWORD}@mongo:27017/

networks:
  dailytrends:
    driver: bridge
volumes:
  mongodailytrends:
    driver: local